---
services:
  nexus:
    image: sonatype/nexus3
    restart: always
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"
      - "8085:8085"
    networks:
      - it4innov-app
networks:
  it4innov-app:
    driver: bridge
volumes:
  nexus-data: {}