---
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    volumes:
      - "jenkins-data:/var/jenkins_home/"
    ports:
      - "8083:8080"
      - "50000:50000"
    networks:
      - it4innov-app
    user: jenkins
networks:
  it4innov-app:
    driver: bridge
volumes:
  jenkins-data: {}
